### ISSUE TITLE
Monk Unarmored Movement Issue?

### ISSUE THREAD

**Issue by ColdAnkles** [aurorabuilder/elements#112]
RAW: Unarmored Movement grants additional walking speed.

Sage Advice (https://www.sageadvice.eu/2015/07/22/aaarakocra-monk-unarmored-movement/) says it applies to all speeds, flying and presumably climb and swim too.

**Comment by swdriessen** [comment]
Hmm, will have to do some tests.
Don't want double stacking when you have a feature that gives you a swim speed equal to your walking speed and then adding this unarmored movement twice as a result.

**Comment by Gherrick** [comment]
Is base move a separate value from modifiers? If so, then the effects that give new move modes can just change the base move value. The character sheet formulas could display base + sum(mods), and use a hierarchy to determine which base value to use (something like Race, Class, Feat, Equipment would work for most cases).

**Comment by swdriessen** [comment]
There is a stacking bonus for base speed but not a seperate value, but it's something i will address in an upcoming statistics update.
Main reason is the AC stat because it's a stacking bonus nightmare when there are too many conditions which i will refactor in multiple 'base' stats _(unarmored/armored/natural armor/unarmored defense barb/ unarmored defense monk/etc)_ which are then are compared to eachother for the highest (or user selected) formula.

I'll probably include the 'innate' speeds seperate like for example _'acrobatics', 'acrobatics proficiency' and 'acrobatics misc'_ is currently or _'spellcasting:dc:base' and 'spellcasting:dc:proficiency'_. It will most likely be a minimal for these core stats, a stat:base/stat:misc for example.

I'm still working on a full list of all stats before i start implementing anything since it will touch pretty much all content and should be replace in one go, not multiple updates.

**Comment by swdriessen** [comment]
This should work with v1.19.304 & the updated files. I've tested several combinations, re-open if anything is incorrect.
