### ISSUE TITLE
Custom Collections.

### ISSUE THREAD

**Issue by benfinn** [aurorabuilder/elements#125]
Looking at the XML for the collections, is it possible to make your own and simply host them on your own site?

**Comment by ColdAnkles** [comment]
To my knowledge, yes. But you would need to drop in/edit a .index to point to it if you wanted it included in this.

Reading "elements/core.index" the <files></files> block defines arbitrary files and their URL.

**Comment by swdriessen** [comment]
Yes. I just use github because it makes a lot of things so much easier to maintain, share, allow contributions, issue reports and fixes, questions, etc.

You can create a benfinn.index link to your own files using own url's. You can then share the url of this index file so others (or yourself) can include it in the builder using 'additional content' tab.

When you then update your hosted files (and increase the version number at the top) the builder will update them automatically (using the new update).
