### ISSUE TITLE
Not all spell cards are generated in character sheet PDF.

### ISSUE THREAD

**Issue by Magneseus** [aurorabuilder/elements#16]
Unsure if this is a known issue, but when I generate the character sheet not all spells are included in the spell cards at the bottom.

eg: A Grave Cleric

Prepared Spells:
- Light
- Mending
- Spare the Dying
- Toll the Dead
- Bane
- Cure Wounds
- False Life
- Guiding Bolt
- Healing Word
- Inflict Wounds
- Continual Flame
- Gentle Repose
- Lesser Restoration
- Prayer of Healing
- Ray of Enfeeblement

Spells that show as cards in the PDF:
- Light
- Mending
- Spare the Dying
- Toll the Dead
- Bane
- False Life
- Gentle Repose
- Ray of Enfeeblement

**Comment by chrisjfoss** [comment]
I believe this is a known issue, I remember seeing it discussed elsewhere, but I can't find it right now.  

If I'm not mistaken, this occurs because of the way the spells are applied to the cleric.  Light, Mending, Spare the Dying, etc show up because you were granted knowledge of them through your specific domain.  Clerics as a whole however get immediate access to the entire cleric spell list whenever they reach the appropriate level, and however this is handled, it is not creating the spell cards.

This would also be why the issue only occurs for those classes that get immediate access to the whole spell list, such as clerics and druids, as opposed to wizards which have to specifically choose which spells from the list they want to learn when they level up.

I don't personally know of any workarounds for this, short of possibly going into the markup for the cleric class or the grave domain and granting yourself each spell individually - which I haven't tested, but assume would work.

I believe swdriessen is planning on reworking the pdf generation after he implements the support for equipment, but I'm not 100% certain.

**Comment by Magneseus** [comment]
Ah that makes sense, thanks for the explanation. Not too big a deal, just a nice QoL change.

Thanks!
