### ISSUE TITLE
Content Request - homebrew subclass

### ISSUE THREAD

**Issue by robnessmonster** [aurorabuilder/elements#168]
I apologize if this is the wrong place for this request.

I am trying to make a homebrew subclass for Elf. I am failing miserably. 

The idea is a variant on High elf, except it has no magic abilities.  No cantrip, no +1 Int, instead it gets a feat at level 1.
If this is possible, perhaps someone can help me not be dumb, or set a file up for me.

**Comment by NickVendel** [comment]
It's not that easy since Variants require changes in original race, and if it's updated then all the work is gone. I would strongly suggest to always ask help on [Discord](https://discord.gg/Hxkn7xF), if you need something for personal use, rather than to request some specific content from other sources.
I recommend to look up how Human Variant (probably all Human file) is done. Copy Elf race file, put it in custom, and then change it to suit your needs, adding Variant in and adding negative requirements to original Race.
