### ISSUE TITLE
UA School of Invention (Archetype)

### ISSUE THREAD

**Issue by swdriessen** [aurorabuilder/elements#2]
The school of invention arcane tradition from this [Unearthed Arcana](http://dnd.wizards.com/articles/unearthed-arcana/three-subclasses) article.

[unearthed-arcana/2018/20180108.xml](https://github.com/aurorabuilder/elements/blob/master/unearthed-arcana/2018/20180108.xml)

**Comment by chrisjfoss** [comment]
I'm willing to tackle this one, but I'd appreciate some thoughts on the Reckless Casting feature.  That is a lot of space for a feature, and it looks to me like it really should be put in the features and traits section, since the player will actively need that information to use the feature.  

I will obviously restrict the sections so they only see the tables that they can make use of at their level, but that will only mitigate the problem until they level up a bit.  

I added a feature idea to the reddit (feature and trait cards), which if implemented might allow me to move this section to a card or series of cards, and thereby reduce the information displayed in the features and traits section.  I might be able to make a hack for that behavior by treating the tables as a spell, but I don't know if I can both get it into a card and keep it off of the character's spell list. I'll look into that.  

Regardless, I'll hold off on this one until I am sure regarding where to put the tables for the Reckless Casting feature.

Afterthought: Perhaps instead, I should find a way to get each of the individual spells onto a spell card, with an "id" appended to each of them - perhaps in the title? - indicating the die roll that they get cast on.  Then in the sheet description, I describe only what happens on a roll of 10, and direct the rest of the rolls to the card with the appropriate id and casting level?

**Comment by chrisjfoss** [comment]
Honestly, I could put "Reckless Casting" as a spell under each spell level from Cantrip to 5, and then the sheet description would simply say you get access to Reckless Casting spells.  The spell cards for the Reckless casting spells would then hold the tables individually, and I can make them prepared by default.

Personally, that's how I think I would prefer to do it, but it would require I change some of the wording from the pdf, so I'll still wait for feedback.

**Comment by swdriessen** [comment]
The main issue is the lack of space in the standard character sheet. I'm planning to add other sheets that are better designed and for example seperate pages for all features and spells.

The cards are a preview feature at the moment, i've got plans to add more cards for things such as attacks with equipped weapons or cards with details for other equipped items. But for now it's limited to spells. 

I'd go about it simply putting in the basic description including the reroll on 10. The player can either have the tables or with them as a print or pdf for reference. There are more table such as wild magic table that require the player to have them available to them. 

You could also make an element for each table and grant these elements in the main feature. Then you have seperate sheet descriptions available to you for each table.

_Reckless Casting (Cantrip). 1 acid splash, 2 chill touch, 3 fire bolt, 4 light, 5 poison spray, 6 ray of frost, 7 shocking grasp, 8 sacred flame, 9 thorn whip, 10 reroll._

_Reckless Casting (1st-level). 1 burning hands, 2 chromatic orb, 3 color spray, 4 faerie fire, 5 false life, 6 fog cloud, 7 jump, 8 magic missile, 9 thunderwave, 10 reroll._

Since the builder is in preview it should be fine like this. We can always improve on it later once a feature is added.

**Comment by chrisjfoss** [comment]
I finished the School of Invention (sorry about the delay - I went on vacation), but I am not sure whether to replace the AC displayed on the sheet with the arcanomechanical armor's AC. Currently, I am leaving the AC with the arcanomechanical armor in the sheet description instead of affecting the AC, but a second opinion would be nice.  I will go ahead and make the pull request as is.
