### ISSUE TITLE
Epic Levels or Multiclass (level 21+ characters)

### ISSUE THREAD

**Issue by RevCivic** [aurorabuilder/elements#213]
**Additional context**
One of my groups' character parties is over level 20. I was just thinking wondering if the cap could be lifted, or if a setting could be added to go over level 20. I'd be happy to make my own content for it, but I need the ability to increase their levels.

Thanks!

**Comment by NickVendel** [comment]
Just to be clear, levels here are not "at cap", or something. Characters just have a line that say that they have a particular level, and it gives you something that was already appointed at that level (including HP, features, proficiency bonus, etc.), and because there's no official rules for _Epic Levels_ even if @swdriessen simply would add 21+ levels to app itself, they will be absolutely empty.

**Comment by RevCivic** [comment]
What if there was just a standard increment assigned. Obviously your hit dice would remain the same and you would gain that much health per level. And your feats/ability score improvements could happen every X number of levels after 20. Something simple since WOTC didn't implement a method of going "epic".

Also a simple addition that could be added that is more rules savvy, is the ability to take multiple classes to level 20. So a multi class build could reach level 11 in 2 separate classes without an issue (or someday maybe level 20 in 2 or 3 classes). I know it would be super OP but I feel like there should be some method to continue improvement. 

If the simple CAP was raised, I could write my own XML files to define what happens after 20. 

It isnt a huge or emergency request, I just know in the past I've calculated the XP required for level up dynamically in Ruby, Java, Javascript, and Excel formulas before and those formulas could go on indefinitely using the "next level" button. Being small amounts of code I just thought it could be a simple improvement. The builder is great so far, and has saved me from going back to 4E, which supports infinite level ups in it's own way.

Thanks

**Comment by swdriessen** [comment]
The level cap of 20 is somewhat hardcoded currently so this isn't something i'll change soon since there are other things i'll have to spend my time on.

The 5e way of going epic is not in the form of leveling up but giving rewards when you're at level 20. Blessings, Charms, Marks of Prestige, and Epic Boons. Also, optionally an ability score increase (max raised to 30) or a feat like the ones you get at 4th level and above.

These have not been implemented yet and will be added before including homebrew options such as this.

What you currently can do is to create an option element (like optional [firearms rule](https://github.com/aurorabuilder/elements/blob/23dc208c84734ec1b770d3b1ad1601e266c08dd1/core/dungeon-masters-guide/items/items-firearms.xml#L11-L19)) that a player can select from the manage options list. You can grant elements from that element with the level 20 requirement. You can have them select extra feats, or give a bonus to hp for example.

**Comment by NickVendel** [comment]
@RevCivic I understand what you want to do, but i think i'm correct when saying that there's no _cap_ per se (@swdriessen though knows better of course), it's more like every level is hardcodded in. And even if you would add level 21, for example, you would still need to go through every class and add elements for that level and every other level after over 20. Similarly, you will need to change ASI and spellcasting features for every class. It's a massive job.
And as @swdriessen said, you can just create option to give you stuff, like "Option: Level 21" that gives you another Fighting Style, or something like that.
