### ISSUE TITLE
When building a Rogue Proficiencies 

### ISSUE THREAD

**Issue by NobodyisOutis** [aurorabuilder/elements#218]
**Describe the issue**
When I add proficiencies (Expertise) to the rogue, it wouldn't let me double proficiency even though rogues can do that, (If I remember correctly).  Especially when you get to level 6 is when the issue comes up.  IT's a small issue but I just thought I would bring it to people's attention. Thank you for reading.

**Comment by Azzzzzy** [comment]
Have you alrwady chosen proficiencies from the proficiency tab? Since the expertise list won't have anything unless you've already selected a proficiency to begin with.

**Comment by NobodyisOutis** [comment]
No, It`s before I get to the proficiencies tab. Do you think it has anything to do with the different subclasses of rogue? I don't seem to have any trouble with the scout subclass of rogue. But the other subclasses, I have the issue with. 
![キャプチャ](https://user-images.githubusercontent.com/47868001/54082945-74fa6880-4360-11e9-8121-8faef13d58a2.PNG)

**Comment by Azzzzzy** [comment]
Yeah thats just a weird logic flow in the program if you select all your proficiencies first it will immediately update the expertise sections. The reason you don't see it with it the scout subtype is because the scout subtype gives you  nature and survival proficiencies. If you choose your background and proficiencies first before doing the expertise it should work as normal simply disable "Selection Flow" at the bottom while choosing proficiencies and then re-enable it after you're done.

**Comment by NickVendel** [comment]
Yeah, @Azzzzzy is right. Before choosing Expertise in skill you need to have Proficiency in it. Maybe it's better to make selection for expertise `type="Proficiency"`, so it would displayed in that tab.

**Comment by NobodyisOutis** [comment]
Oh ok, thank you so much for telling me! I was wondering why it was doing that. Thank you!
