### ISSUE TITLE
Multiclass issues

### ISSUE THREAD

**Issue by ArturMorgen** [aurorabuilder/elements#317]
When I make a character with the Mystic class I am unable to multiclass into any other classes. Also I cannot choose mystic to multiclass into.

**Comment by NickVendel** [comment]
Mystic doesn't have Multiclass, if you want it, then edit class' file and add any requirements you want.

**Comment by LoZeno** [comment]
I encountered the same issue and I tried to create a multiclass element in my user content folder, using the <supports /> tag, thinking that that way I could "add" the multiclass feature to an existing class, but it didn't work. I don't understand if it's a bug or a desired effect, though? It would make homebrew content easier to create

**Comment by swdriessen** [comment]
This is one of those edge cases in the playtest material since they didn't include the rules for multiclassing the mystic. 

Currently you can create an elements file in `custom\user` and override (copy/paste) the class element entirely (and override what ever multiclass requirements you want). You only need the class element in there for it to work, this way you don't have to touch the files downloaded by the index file.

In the future you'll probably be able to override the multiclass part (or append it when it's non-existing) seperate instead of overriding the class element.
