### ISSUE TITLE
Cannot create a Dwarf Variant race

### ISSUE THREAD

**Issue by LoZeno** [aurorabuilder/elements#321]
I can't find a way to create a Variant race for the Dwarf. For various reasons (homebrew setting) a Subrace doesn't fit the concept, so I was trying to create a variant race with very different stats and racial features; I followed the same format as the various Human variant races available, but when I try to use my Dwarf variant race, it doesn't show up in the race selection.

**Comment by NickVendel** [comment]
_Variant_ as an alternative to _Subrace_, and even though you can make Variant for Race with Subraces, there's no reason to, since there's no difference code-wise between them. Just create another subrace for Dwarf and use all stat's you used for Variant, don't forget to put `requirements="![ID_OF_YOUR_VARIANT_HERE]"` into stats/grants/selects of original race, if you want them removed, when using your version.

**Comment by LoZeno** [comment]
Got it! Thanks. I just found out that I can even change the text on the <select> element to say "select variant race" instead of sub race, even if it technically is a sub race.
