### ISSUE TITLE
"Magic" items with different bonuses to attack and damage

### ISSUE THREAD

**Issue by LoZeno** [aurorabuilder/elements#323]
I'm creating a homebrew conversion of DarkSun. Among the million things that DarkSun makes more complicated, there's the matter of non-metal weapons (obsidian, wood, bone are the most common materials); each material gives negative bonuses (maluses?) to attack and damage to the weapon (plus reducing costs and weight), so the way I'm doing it now is to create new elements of type "Magit Item" and category "Magic Weapons" that work like, for example, "Weapon +1": you select the weapon, then select "Obsidian Weapon", and it applies the -1 "enhancement".

So far so good. The problem is that, ideally, the negative enhancement to attack could be -1, but the negative enhancement to damage could be 0 (in the case of obsidian weapons).
Bone weapons would have a -1 to attack and -1 to damage, a wood weapon -1 to attack and -2 to damage. The Magic Item element, in the setters, has only the "enhancement" set, which if I understand it right applies to both attack and damage. Is there a workaround to give different enhancements to attack and damage instead?

This is what I've done so far:
```
<!-- Obsidian Weapons -->
    <element name="Weapon, Obsidian" type="Magic Item" source="Dark Sun 5e Conversion" id="ID_DARKSUN_OBSIDIAN_WEAPONS">
        <description>
            <p>Weapons made of Obsidian have a -1 to attack and damage</p>
        </description>
        <setters>
            <set name="category">Magic Weapons</set>
            <set name="cost" currency="cp">0</set>
            <set name="weight" lb="0">0 lb.</set>
            <set name="type" addition="any">Weapon</set>
            <set name="rarity">Common</set>
            <set name="enhancement">-1</set>
            <set name="weapon">ID_INTERNAL_WEAPON_CATEGORY_SIMPLE_MELEE||ID_INTERNAL_WEAPON_CATEGORY_SIMPLE_RANGED||ID_INTERNAL_WEAPON_CATEGORY_MARTIAL_MELEE||ID_INTERNAL_WEAPON_CATEGORY_MARTIAL_RANGED</set>
            <set name="name-format">Obsidian {{parent}}</set>
        </setters>
        <rules />
    </element>
```

**Comment by NickVendel** [comment]
That's why when creating my Stone Age campaign, i just stuck with normal damage/attacks, explaining it with "well, armor is also shit and rock can still kill you". But yeah, i'll check if there's a way to do this

**Comment by NickVendel** [comment]
okay, well, there's two ways to do this:
1. Select any weapon you need, change it's name through right-clicking and selecting _Item Details_, then click "ADD [Weapon Name] TO ATTACKS" and then go to **Manage**/**Attacks & Spellcasting**, select your weapon and edit its attack to be -1 to hit. So you don't need file for this.
2. You can alternatively put this into your Magic Weapon, while changing `<set name="enhancement">-1</set>` to 0:
```xml
	<rules>
		<stat name="melee:attack" value="-1" />
		<stat name="ranged:attack" value="-1" />
	</rules>
```
The only problem is that it would apply to every weapon when equipped, since it's a _character stat_ not the _item set_.
So i would recommend to use first option, since you don't need new files and it's fairly quick to do.
I would still argue that there needs to be separate attack and damage sets for weapons, like one of my weapon upgrades/properties (Aged) gives bonus to attack but doesn't give bonus damage, and there's also upgrade that does the opposite (Sharp). And weapons can be both Aged (basically means that it consumed enough magic throughout the years, to become Magical Weapon) and Sharp, while also have bonus to enchantment like Weapon +1. I hope this going to be the way, when Magic Weapons will be reworked into "Enhancements"(/"Properties", or something like that), where you can stuck one on another.

**Comment by LoZeno** [comment]
Thanks, I think I'll go with the first approach you suggested (for now). It's a bit annoying because it will require me to manually update the values each time the characters gain levels, since it overrides the attack and damage calculations, but I can't see a better way so far.

BTW, the reason why I didn't follow the approach you used for your Stone Age campaign is that in DarkSun there are metal AND magic weapons, they are just super rare - but they are there. So a normal metal longsword will deal the normal damage and have no penalties to attack, the wood, bone and stone versions will have different maluses.

**Comment by NickVendel** [comment]
Yeah, no i understand, i'm just saying that it's why i wasn't doing any kind of bonuses/minuses to attacks/damage, since it's my and my player's first time and throwing more complicated stuff, would just... complicate stuff XD
If i was in your place, i would also stick to setting rules. And yeah, it's annoying to change stuff every level, yet right now, i think it's the best option. Good luck with your Conversion.

**Comment by erjicles** [comment]
Just my 2 cents, I think this would be nice to have as well. There are a couple of homebrewed magic items in my campaign that have different attack and damage bonuses and it would be great to have this be able to handle that situation.

**Comment by swdriessen** [comment]
This content repository is being archived. I am closing any pending issues and pull requests.
I'll be sharing more information about concrete changes at a later date on the website.
