### ISSUE TITLE
Content Request - [Homebrew] Universal Wizard School & Arcane Sorcerer bloodline

### ISSUE THREAD

**Issue by biggamac** [aurorabuilder/elements#338]
I'm not confident in my coding to do this myself but if someone has the time and inclination I'd love to see these in Aurora Builder.
Cheers.

[Wizard - Universal School.pdf](https://github.com/aurorabuilder/elements/files/3368360/Wizard.-.Universal.School.pdf)
[Sorcerer - Arcanist.pdf](https://github.com/aurorabuilder/elements/files/3368361/Sorcerer.-.Arcanist.pdf)

**Comment by NickVendel** [comment]
"**Universal School**" also known as **Lore Mastery**. I mean, it's literally the same premise.

**Comment by biggamac** [comment]
Hey NickVendel,
I'd never even heard of the Loremaster class. Is it official content or also homebrew?

The idea behind the Universalist gaining meta magic is that by not focusing on a specific school, they gain a greater understanding of magic as a whole, and thus can find ways to enhance their spellcasting. Hence metamagic.

For the Arcanist bloodline... you're right, lore wise the flavour text makes no sense. But could also represent sorcerers whose magic is specific. For example a changeling having an innate ability with illusion magic. Or the child of a powerful transmuter. 

Part of my desire for these classes is having come across from pathfinder where metamagic are feats available to any spellcaster and the sorcerer spell list is less restricted.

**Comment by NickVendel** [comment]
> The idea behind the Universalist gaining meta magic is that by not focusing on a specific school, they gain a greater understanding of magic as a whole, and thus can find ways to enhance their spellcasting.

Yes, i understand the idea, but Wizards can't have Metamagic anyway, since "understanding" doesn't enhance their physical connection to magic. Again, Lore Mastery Tradition does the same thing, but it does it correctly, where by studying magic you understand how to slightly change (let's say) "formulas" of spells to increase/change potential outcome.
And yes, it's official (but it's something like beta-test, it's not yet released in a book form, and maybe never will be), it's Unearthed Arcana article, [here's the link to pdf](https://media.wizards.com/2017/dnd/downloads/20170213_Wizrd_Wrlck_UAv2_i48nf.pdf).
> But could also represent sorcerers whose magic is specific.

Sure, you could still concentrate on one School of magic if you want, i just think it's separate from Origin. And here it replaces your Origin, which as you said makes no sense, since you usually get your abilities from something. Sorcerer always needs to have something that gives them powers like "he was bitten by radioactive spider" or "there was a great big flash, everything just changed, his molecules got all rearranged!" or usually he just inherits abilities of powerful being like Dragon, Devil, Angel, etc.

And it's fine if you want more flexibility, as i said that logic would make some sense in other universes, where magic less strict. Like Dragon Age universe, for example.
