### ISSUE TITLE
Content Request - Custom Items

### ISSUE THREAD

**Issue by Linerunner99** [aurorabuilder/elements#40]
As a DM I often create unique items for my campaign. Armors, weapons, etc with multiple traits rather than the one the current system limits you to and the ability to alter each stat (AC, weight, damage, range, etc) and have those stats reflected on the character sheet when equipped would be very handy.

**Comment by Linerunner99** [comment]
Ok, example of a custom set of armor a player in my campaign has: Plate armor +1 that can shift form to appear as normal clothing. In this form it has a weight of 5 lbs., allows dexterity bonus to AC and no longer imposes disadvantage on stealth checks. Another: Armor of The Eagle - +2 plate mail that can transform the wearer into a giant eagle and absorbs magic missiles cast on it, storing them in the companion Longsword of The Eagle to be used.

Honestly just the ability to enter the stat values for items would help. For instance the dex bonus, attunement, stealth penalty, weight, and such so the stats on the character sheet would reflect custom items. The details of why the stats are different can always be entered on the item's info card.

Also another useful option would be to allow multiple magical properties to be selected for an item. +2 mithril plate for example.

**Comment by swdriessen** [comment]
Armor of the Eagle / Longsword of the Eagle can be made, most of the extra's can be put in the description much like the Demon Armor which is a +1 plate with additional features. I'll see if i can make a small example for these two items this weekend.

The shifting armor is something used in game i guess, if you want it to reflect stats such as dexterity you can unequip it since you don't equip normal clothing. Something as custom as shifting from one to another is more something for a combat tracker type application i think, it requires very specific rules which are not implemented. It's also something the player does on the fly in-game as which point he/she should just take into account the calculation for the period the armor is shifted.

I do plan to add conditional stats that should have a spot on the character sheet in the future. For example that when you get '+2 AC when no allies next to you' it should be listed on your sheet near the box for AC bonus.

As for multiple magic properties, i am planning to add this. Until then you could create a custom item that does the same. Altering stats of items such as weight will also be added in the future.

**Comment by Linerunner99** [comment]
I don't believe unequipping the armor would be a good solution as it would remove the armor class as well as the penalties (it has full armor value in clothing form as well as normal form), but if you're adding the ability to modify those values it'll be fine. I would simply do it that way. Until that feature is added I'll just have the abilities noted in the description and note the stats on the sheet manually.
