### ISSUE TITLE
Adding hit dice / points.

### ISSUE THREAD

**Issue by benfinn** [aurorabuilder/elements#443]
**Describe the issue**
I'm making some homebrew monster classes, and I'd like them to start off with more hit dice and/or hit points than their class level. I assume this is something I'd put in the custom race file, but can't find anything in the XML files to indicate what I should use for that, or if it's even possible.

**Comment by swdriessen** [comment]
I'm not sure about monster classes as opposed to monster races but since it's implemented using the official rules, currently you can only have 1 hd / class level.

You can however add extra hp based on the level of the class (or level of the character if added as a racial trait).
`<stat name="hp" value="level" />`

When you want to give 2 extra hp / level you just add this rule two times. You can of course still use any value here.
`<stat name="hp" value="50" />`

Rule wise you might give them a trait or class feature that lets them regain hit dice after a short rest or gain extra hp back when using a hit dice to keep in line with the official rules.

**Comment by benfinn** [comment]
I meant to say "races," and thank you, this will solve my problem handily.
