### ISSUE TITLE
Content Request - The Magus Class

### ISSUE THREAD

**Issue by J75057exe** [aurorabuilder/elements#457]
The magus class is a martial-magic blend class by Benjamin Huffman. Its on DMs guild for £3. worth it imo and id really like to have it in aurora as well

**Comment by swdriessen** [comment]
I've added it, feel free to test it.

**Comment by J75057exe** [comment]
woah, I have no idea how you made that so fast. I just updated it and it popped up with like 4 error like this:
![image](https://user-images.githubusercontent.com/32099438/72683504-5113c180-3af1-11ea-8ce6-a9c1c0d7c2df.png)
I don't know how to fix this. Isit just a case of clicking out of the messages? it seems to work fine afterwards and im currently making my new character. sorry for bugging you, I really love the app

**Comment by swdriessen** [comment]
Ah yeah, i forgot to test creating a higher level character from the 'new character' instead of leveling it. It probably only pops up at the start when creating a character of level 2 or higher.

It's todo due to the nature the spellcasting works for the magus, with a different spellcasting depending on archetype.

I'll add some requirements i had back in to prevent this.

**Comment by swdriessen** [comment]
Should be fixed
