### ISSUE TITLE
Monk Tradition: Way of Shadow missing spell cards

### ISSUE THREAD

**Issue by Gherrick** [aurorabuilder/elements#48]
Shadow Arts. As an action, you can spend 2 ki points to cast darkness, darkvision, pass without trace, or silence, without providing material components. Additionally, you gain the minor illusion cantrip if you don’t already know it.

Minor illusion spell card is listed, but none of the other spells. Please add the other spell cards if possible.

Edit: I didn't realize how simple it was to add them! I proposed a change to address this issue.

**Comment by swdriessen** [comment]
This needs some internal work since you're not actually getting the spell but can _**duplicate the effect**_ of a spell. You can grant the spell to make the card show up but then you can't select the spell if you multiclass in a spellcaster since you already have the spell.

I will include an option in the future to add any spellcard to the sheet without actually having the spell, but just to use it as reference.

**Comment by Gherrick** [comment]
The ability literally says "to cast". Is it because it doesn't use the "Cast a Spell" action?

**Comment by Gherrick** [comment]
The way of the sun soul path includes the Burning Hands spell on the character sheet, and the wording for Searing Arc Strike is the same as in Shadow Arts.
