### ISSUE TITLE
Steel Defender Might of the Master Missing Rend and Repair

### ISSUE THREAD

**Issue by zacharyrs** [aurorabuilder/elements#484]
**Issue Description**
As the player proficiency increases, the companion skills (athletics, perception), and saves (dexterity, and constitution) increase correspondingly. The stats for the Force-Empowered Rend and Repair don't seem to, but they should also increase.

**Additional context**
https://github.com/aurorabuilder/elements/blob/master/supplements/eberron-rising-from-the-last-war/class-artificer.xml#L903

**Comment by swdriessen** [comment]
Yes, they should, but it's a current limitation for companions and their descriptions.

No details on when/if it will be included.

**Comment by zacharyrs** [comment]
Ah I see, so I take it the templating doesn't parse through companion descriptions then?

Guess I'll just keep my eye on it then!

**Comment by swdriessen** [comment]
Correct, those descriptions are static. They are also not added through rules (there are exceptions) etc.

You could make a workaround for yourself if you wanted. Create a class feature with the description of the companion feature, and add statistic rules that you include in that sheet description which will then show up in your character's features and traits instead of on the companion sheet. But the artificer features are already extensive to the point that it would probably just clutter your class features.

A manual entry in the additional features or notes page would be wise. Or perhaps manually add an attack, or in the section under attacks on the main sheet.
