### ISSUE TITLE
Some boxes not editable on form fillable sheet

### ISSUE THREAD

**Issue by ChellieH** [aurorabuilder/elements#512]
There are quite a few boxes (like the traits boxes and the item cards descriptions) on the form fillable character sheet that are not editable. It would be great of we could edit everything. Sometimes we have slightly amended classes who's changes aren't worth a full index file or want to add notes when rules have been clarified (or tweaked by the DM)

**Comment by swdriessen** [comment]
When you don't want to additional formatting in features and traits for example you can turn off the formatting setting for it. You don't have this option for cards due to the implementation.

Only the equipment sheet makes use of new implementations where you can edit everything on the page, and almost everything, (show/hide/edit descriptions) from the software. 

In the current development v1.0.3 is the last version for quite some time and no updates will be made in the (near) future. (see website for [updates](https://aurorabuilder.com/posts/tag/update/))
