### ISSUE TITLE
Move Rogue Expertise to Proficiencies

### ISSUE THREAD

**Issue by mhoffman52** [aurorabuilder/elements#525]
When first using your app I was using the Selection Flow, I got stuck on class and Rogue Expertise, the app wouldn't move forward unless I selected a skill. The issue, I only had thieves tools available. I had to pick my back ground, setup my ability scores then I could go back to class to setup Expertise.

**Comment by swdriessen** [comment]
The selection flow is very basic but is still useful (hence auto-flow is disabled by default instead of removed for v1.0) it will skip selections that have no options left to choose in the future. Since the rogue expertise is a class feature will keep it in the class tab. I try to minimize making changes to elements for issues that need to be solved in the code to keep it maintainable for myself.
