### ISSUE TITLE
DMSGUILD Classes   (happily help if shown how)

### ISSUE THREAD

**Issue by liam-pirie** [aurorabuilder/elements#533]
The Duelist:
https://www.dmsguild.com/product/254917/The-Duelist--A-5th-Edition-Class
The Grave Warden: 
https://www.dmsguild.com/product/252076/The-Grave-Warden--A-5th-Edition-Class
The Titan: 
https://www.dmsguild.com/product/258424/5th-Edition-Class-The-Titan
**The Spiritualist:**(done)
The Paragon:
https://www.dmsguild.com/product/286312/The-Paragon-Class-5e
The Dancer:
https://www.dmsguild.com/product/205334/The-Dancer-5e-Class
The Dragon-lord:
https://www.dmsguild.com/product/221426/Dragon-Lord-Class
cleric subclass- Elemental cleric domains:
https://www.dmsguild.com/product/248406/Elemental-Cleric-Domains--A-5th-Edition-Cleric-Domain-Collection
The Swordmage:
https://www.dmsguild.com/product/224413/Swordmage-A-True-Arcane-HalfCaster-for-5e
The Alchemist:
https://www.dmsguild.com/product/194341/The-Alchemist-5e-Class-w--4-Archetypes
**The Magus:**(done)
**The Pugilist:**(done)
The SpellBinder: 
https://www.dmsguild.com/product/195427/The-Spellbinder-Class
The Summoner:
https://www.dmsguild.com/product/213716/The-Summoner-5e-Class
The Elementalist:
https://www.dmsguild.com/product/216381/OAP-The-Elementalist-Class
The Mistwalker:
https://www.dmsguild.com/product/241129/The-Mist-Walker--5e-Class

**Comment by Azzzzzy** [comment]
Have you downloaded the third-party index? Almost all of the Huffman content is already in the builder and the Grave Warden is still a WIP (basically done just needs some renaming of stuff). The r/UnearthedArcana stuff you should take over to the [Reddit Repo](https://github.com/community-elements/elements-reddit).

**Comment by liam-pirie** [comment]
yeah I do, just noticed three on my list are there,so ill update that, thanks :D.

**Comment by swdriessen** [comment]
Instead of a whole list, make individual requests for content. Also, don't request your wishlist, request the one or two you'd like to see most. Quality over quantity. 

When you want help creating content I suggest you start checking out https://aurorabuilder.com/documentation/ to get started with the basics (xml editor, files in the right place with the right structure, look at existing content for examples, etc), then hop on discord if you need some more help with specifics.

Also when making a request, read this section and make sure the request is in the scope: https://github.com/aurorabuilder/elements/blob/master/.github/CONTRIBUTING.md
