### ISSUE TITLE
Content Request - UA Stone Sorcery for Sorcerer

### ISSUE THREAD

**Issue by typhirz** [aurorabuilder/elements#63]
https://media.wizards.com/2017/dnd/downloads/26_UASorcererUA020617s.pdf

Thanks!

**Comment by professionalzack** [comment]
I am willing to give this a shot. Is there more to this than simply adding the content to `/unearthed-arcana/2017/20170206.xml` ? 

getting started now

**Comment by swdriessen** [comment]
Since the file exists all you have to do is add the elements and increase the version number at the top of the file to indicate changes in the file. 

Example: https://github.com/aurorabuilder/elements/commit/53c2bed2697710c74d255ddd14979f2403460252 here you see the content added and a version increase.

Good luck.
