### ISSUE TITLE
Skeletal Slime race

### ISSUE THREAD

**Issue by prismanticmasque** [aurorabuilder/elements#88]
[Slime Skeleton Player Race _ GM Binder.pdf](https://github.com/aurorabuilder/elements/files/2598341/Slime.Skeleton.Player.Race._.GM.Binder.pdf)

Hi, this is a pretty simple request, so trust me when I say I wouldn't be asking if I hadn't already tried to do this by myself. This race has been approved by my DM but our group uses the Aurora Builder with all our characters, I thought it would be good to try and get this race included so I edited the code from the unearthed arcana additional races content. It didn't work (I have no idea how to code or what I'm doing)
I'll include my "coding" as a text file in this issue, Maybe it will help ¯\_(ツ)_/¯

[skeletal slime test.txt](https://github.com/aurorabuilder/elements/files/2598359/skeletal.slime.test.txt)

**Comment by swdriessen** [comment]
Cool, it looks pretty much correct. Lets start from the top.

**First:** The `<info>` block is mainly for when you want to share (and host) the file so it can be updated using the builder. **You can remove the block if you don't need it.** Otherwise, you need to fill in the blanks (not leaving url= like this since it's not valid xml.

**Second:** The elements need unique IDs or else they will override existing ones. Some of your racial traits still have the ID_WOTC_UA_RACIAL_TRAIT_SHIFTING id's instead of the id's you grant in the rules such as ID_SS_RACIAL_TRAIT_SQUISHY.

Once you fix these small things it should load correctly (tested).

Small note: you can rename the subraces to their full name e.g. **Green** to **Green Skeletal Slime** since the subrace name will be used when selected.

**Comment by swdriessen** [comment]
When you 'grant' the ID_SS_RACIAL_TRAIT_SQUISHY it can't be found. These traits still had the ID_WOTC_UA_RACIAL_TRAIT_SHIFTING Ids on them.

You need to set the ID on the trait elements (example: ID_SS_RACIAL_TRAIT_SQUISHY). 

As for the AC, i recommend looking at the way it's done with the other races such as lizardfolk for natural armor or the barbarian for the unarmored defense. (there is currently a stacking bug with natural armor and unarmored defense combinations so it might be calculated incorrect if you have a combination of such as race/class e.g. lizardfolk and monk)
