### ISSUE TITLE
ravnica option

### ISSUE THREAD

**Issue by SimonVail** [aurorabuilder/elements#92]
Question: Should Ravnica be an option at character creation ? Since there is only limited races avalaibles (Human, Elf(Devkarin, Simic, and Wood Elf), Goblin, Loxodon, Minotaur, Simic Hybrid(Human, Simic Elf, Veldaken base), Veldaken.

**Comment by swdriessen** [comment]
Since it's just a setting like forgotten realms or eberron rather than a rule you can just limit your selections based on the source.

In the future there will be 'source selection' when creating a character. So you select for example phb/ravnica and the content from the other sources won't show up when selecting race/class/background/spells/etc.

This way the options can focus on rule based options as was intended.

**Comment by swdriessen** [comment]
Sure. I've added the placeholder files but not done any of the content itself.

(the loxodon is on the subreddit so best not start there)

**Comment by swdriessen** [comment]
Sounds good!

As for the Devarkin.. they are just drow according to the book, nothing new rule wise as far as i can tell.

**Comment by SimonVail** [comment]
Devkarin are ridiculous when you think they are always surrounded by necrosis and other wonderful decaying stuff. They should be resistant to necrotic damages.

**Comment by SimonVail** [comment]
Do you have a background template ???

**Comment by MidasTheGolden** [comment]
Have any of the Ravnica Backgrounds been implemented yet? I'm wanting to make a ravnica character in a campaign that is set in a Arthurian setting.

**Comment by swdriessen** [comment]
Any progress on the backgrounds? If you haven't had the time yet i'll add them.
